### ISSUE TITLE
MongoDB restart issues

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#2114]
Currently the mongoDB is crashing if memory (cache) gets to big. Which lead to some downtime of the API. A quick and dirty solution is to regularly (crontab) restart the MongoDb process. @rykahsay is looking into cleaner solutions. Seans comments in #1212 might help as well.

**Comment by rykahsay** [comment]
"solution-1" has been in effect for the last two days and I just switched to "solution-2" today, and I am monitoring if memory usage for mongod stops growing. If "solution-2" does not work, I will switch back to "solution-1".


#### solution-1
Restart mongod every 6 hours
```
0 */6 * * * /usr/sbin/service mongod restart
```

#### solution-2
Edit /etc/mongod.conf and set cacheSizeGB to limit the "internal memory" used by mongod for caching
```
storage:
  dbPath: /var/lib/mongo
  journal:
    enabled: true
  wiredTiger:
    engineConfig:
      cacheSizeGB: 10
```

**Comment by rykahsay** [comment]
It looks like 10GB in solution-2 ("cacheSizeGB: 10") was making the portal very slow. I have increased it to "cacheSizeGB: 80" as shown below and the portal seems to be fast again.  I hope this does not bring back the crashing issue.


```
storage:
  dbPath: /var/lib/mongo
  journal:
    enabled: true
  wiredTiger:
    engineConfig:
      cacheSizeGB: 80
```
