### ISSUE TITLE
make -f MakeFile prod Not working. 

### ISSUE THREAD

**Issue by Luke-Johnson-5** [glygener/glygen-issues#977]
On the AWS server for the deployment in the glygen-frontend deployment steps found [here](https://github.com/glygener/glygen-frontend/blob/master/server-installation.md). At the end the command "sudo make -f MakeFile prod" is returning an error. I have spoken to Robel and he told me to reach out to you to find out what I need to install or change to make this command work. Here is the error I am currently getting:
![image](https://github.com/glygener/glygen-issues/assets/144174552/4251281f-7f89-4502-be42-c619fb0bb684)

**Comment by sujeetvkulkarni** [comment]
@Luke-Johnson-5 I believe we will need to add a new compose file and command options for AWS.
prod compose has below args, we will need similar args for aws
```
version: '3.4'
services:
  frontend:
    build:
      args:
        - REACT_APP_ENV=prod
        - REACT_APP_API=https://api.glygen.org
        - REACT_APP_DOMAIN=https://www.glygen.org
        - REACT_APP_BETA_DOMAIN=https://beta.glygen.org
        - REACT_APP_DATA=https://data.glygen.org
        - REACT_APP_SPARQL=https://sparql.glygen.org
        - REACT_APP_BASENAME=/
        - GENERATE_SOURCEMAP_FILES=true
        - PORT=6060
    ports:
      - '6060:80'
``` 

also command line uses below commands, are they supported on aws?
```
	@docker network ls --format='{{ .Name }}' | grep ^${GLYGEN_NETWORK}$$ > /dev/null 2>&1 || docker network create ${GLYGEN_NETWORK};
	@docker-compose -f docker-compose.yml -f docker-compose.prod.yml --project-name glygen-frontend rm --force
	@docker-compose -f docker-compose.yml -f docker-compose.prod.yml --project-name glygen-frontend up --no-start --build
	@docker image prune --force
````
